import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { useQuery, gql } from '@apollo/client';

const GET_TEST = gql`
  query getTest {
    test
  }
`;

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(GET_TEST);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{ data.test }</p>
    </>
  )
}

export default Home
