import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { useGetTestQuery } from '../src/generated/graphql';

const Home: NextPage = () => {
  const { loading, error, data } = useGetTestQuery();

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{ data!.test }</p>
    </>
  )
}

export default Home
